CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS(
    USER_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY_KEY_USER_ID PRIMARY KEY (USER_ID)
);

CREATE TABLE UNITS(
    UNIT_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    IMAGE_URL VARCHAR(300) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    REGION VARCHAR NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    CANCELLATION_POLICY BOOLEAN,
    PRICE NUMERIC NOT NULL,
    AVERAGE_SCORE SMALLINT,
    CONSTRAINT PRIMARY_KEY_UNIT_ID PRIMARY KEY (UNIT_ID)
);

CREATE TABLE REVIEWS(
    REVIEW_ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    SCORE SMALLINT NOT NULL,
    COMMENT VARCHAR(40),
    UNIT_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT PRIMARY_KEY_REVIEW_ID PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FOREIGN_KEY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FOREIGN_KEY_UNIT_ID FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID) ON DELETE CASCADE
);
INSERT INTO USERS VALUES('b5d46ba0-b0e0-4f0e-a399-e796c3969d3b', 'Haris', 'Vrettos', 'username', 'password');
INSERT INTO UNITS VALUES('b5d46ba0-b0e0-4f0e-a399-e796d3569d3a', 'image/url', 'title', 'region', 'description', FALSE, 300, 0);
INSERT INTO UNITS VALUES('b5d46ba0-b0e0-4f0e-a399-e796c3969d3a', 'image/url/2', 'title 2', 'region 2', 'description 2', FALSE, 400, 0);