CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE USERS(
    USER_ID UUID DEFAULT uuid_generate_v4() NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    SURNAME VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY_KEY_USER_ID PRIMARY KEY (USER_ID)
);

CREATE TABLE UNITS(
    UNIT_ID UUID DEFAULT uuid_generate_v4() NOT NULL,
    IMAGE_URL VARCHAR(300) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    REGION VARCHAR NOT NULL,
    DESCRIPTION VARCHAR(300) NOT NULL,
    CANCELLATION_POLICY BOOLEAN DEFAULT FALSE NOT NULL,
    PRICE NUMERIC NOT NULL,
    AVERAGE_SCORE SMALLINT,
    SEARCH_TOKENS TSVECTOR,
    CONSTRAINT PRIMARY_KEY_UNIT_ID PRIMARY KEY (UNIT_ID)
);

CREATE TABLE REVIEWS(
    REVIEW_ID UUID DEFAULT uuid_generate_v4() NOT NULL,
    SCORE SMALLINT NOT NULL,
    COMMENT VARCHAR(40),
    UNIT_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CONSTRAINT PRIMARY_KEY_REVIEW_ID PRIMARY KEY (REVIEW_ID),
    CONSTRAINT FOREIGN_KEY_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FOREIGN_KEY_UNIT_ID FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID) ON DELETE CASCADE
);