CREATE TABLE REFRESH_TOKEN_WHITELIST(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USER_AGENT VARCHAR(300) NOT NULL,
    USERNAME VARCHAR(40) NOT NULL,
    REFRESH_TOKEN VARCHAR NOT NULL,
    CONSTRAINT PRIMARY_KEY_RTW_ID PRIMARY KEY (ID)
);

CREATE TABLE AUTH_ROLE(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    ROLE VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY_KEY_AR_ID PRIMARY KEY (ID)
);


CREATE TABLE AUTH_ROLE_TO_USERNAME(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    USERNAME VARCHAR(40) NOT NULL,
    ROLE VARCHAR(20) NOT NULL,
    ROLE_ID UUID NOT NULL,
    CONSTRAINT PRIMARY_KEY_ARTU_ID PRIMARY KEY (ID),
    CONSTRAINT FOREIGN_KEY_ARTU_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID) ON DELETE CASCADE
);

CREATE TABLE AUTH_ROLE_TO_AUTHORITIES(
    ID UUID NOT NULL DEFAULT uuid_generate_v4(),
    ROLE VARCHAR(20) NOT NULL,
    ROLE_ID UUID NOT NULL,
    AUTHORITIES VARCHAR NOT NULL,
    CONSTRAINT PRIMARY_KEY_ARTA_ID PRIMARY KEY (ID),
    CONSTRAINT FOREIGN_KEY_ARTA_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AUTH_ROLE (ID) ON DELETE CASCADE
);
