CREATE INDEX INDEX_ROLE ON AUTH_ROLE (ROLE);
CREATE INDEX INDEX_USERNAME ON AUTH_ROLE_TO_USERNAME (USERNAME);
CREATE INDEX INDEX_COMPOSITE_USERNAME_USER_AGENT ON REFRESH_TOKEN_WHITELIST (USERNAME, USER_AGENT);
